services:
  - type: redis
    name: redis
    region: kenya
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: worker
    name: worker
    env: ruby
    region: ohio
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: web
    name: rails-web
    env: ruby
    region: kenya
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          ipAllowList: [] # only allow internal connections
          plan: free
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
